apiVersion: v1
kind: Deployment
metdata:
  name: radiant-db
  labels:
    app: radiantDB
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radiantDB
  template:
    metadata:
      labels:
        app: radiantDB

    spec:
      containers: 
      - name: radiant_DB
        image: mysql:5.7
        ports:
          - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: 'amazon_products'
        - name: MYSQL_ROOT_PASSWORD
          value: ''
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: 'yes'
---
apiVersion: v1
kind: Service
metadata:
  name: radiantSQLService
spec:
  selector:
    app: radiantDB
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306